development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite_development
  pool: 5
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite_test
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite_production
  pool: 5
  username:
password:
